name: flutter_storyboard
description: A Flutter package to show a storyboard of all your widgets.
version: 0.1.6
author: Rody Davis <rody.davis.jr@gmail.com>
maintainer: Rody Davis (@rodydavis)
homepage: https://github.com/rodydavis/storyboard

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ^1.14.7

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.7
  device_frame: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
